---
- name: install and start service
  hosts: localhost

  tasks:
  - name: installing nginx
    apt:
      name: nginx
      state: present
  - name: starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true
